### ISSUE TITLE
Using DeFacto score to discover evidence

### ISSUE THREAD

**Issue by anikethjr** [DeFacto/DeFactoNLP#1]
Code a function `defacto_evidence_retriever(claim, potential_evidence_sentences)` where `claim` is the statement whose veracity we have to determine and `potential_evidence_sentences` is a list of sentences which could possibly support or refute the claim or provide no relevant information. The function should return a dictionary called `results` which will have three fields:

1. `claim`: the original claim
2. `label`: overall classification for the claim - SUPPORTS, REFUTES or NOT ENOUGH INFO
3. `evidence`: if the `label` is SUPPORTS or REFUTES, then it is the list of sentences which either support or refute the claim else it is an empty list

**Comment by pedrojlazevedo** [comment]
Currently, this task is separated into two.
The first one the RTE model is providing a potential label for the potential_evidence_sentences. 
The second one is done by the Random Forest model. With the potential evidence and the labels from the RTE model, it will conclude the label and the evidence that supports the label.
