### ISSUE TITLE
Determine Label and supporting evidences given RTE predictions

### ISSUE THREAD

**Issue by GilRocha** [DeFacto/DeFactoNLP#4]
Inside `textual_entailment_evidence_retriever(claim, potential_evidence_sentences)` there is a function called `determinePredictedLabel(preds)` that given the RTE predictions determines the label and supporting sentences.

## Aim: 
improve `determinePredictedLabel(preds)` function

## Current version:
Returns the label predicted more times given the evidences and all the evidences with the corresponding predicted label

## Ideas:

1. @Aniketh:  After getting the number and confidence of sentences which support, refute and are neutral, we could supply these numbers to another classifier (like a fully connected NN or SVM) to perform the final label determination. Another similar approach could be used to determine which possible evidence sentences are to be finally given as outputs.

Questions:
@Aniketh Do you have suggestions on how to formulate the problem? 

Suggestions:
- @Gil: 
	- Part 1: feature representation something like `(SupportScore, ContradictionScore)`, where `SupportScore` is the max confidence score given to a "Entailment" prediction that the RTE model gave to an evidence, `ContradictionScore` similarly. Labels for this task would be [Support, Contradiction, NotEnoughInfo]
	- Part 2: feature representation *WIP*

2. How to obtain some measure of factuality/veracity of given evidence? (recall that the RTE model just tell us how much a given evidence can be used to support the claim, it does not judge the veracity of the evidence)
	- Train a model to determine how factual the evidence is? Is there related work on this? Is there existing models that we can use? Is there something wikipedia specific to determine the veracity of sentence (@Diego work? Wikitables? Knowledge bases?)
	- Recursive approach!!! Run the code again but now the claim is the evidence ... then if we obtain supporting sentences labeled as "Support" it means that it is true! If we obtain supporting sentences labeled as "Contradiction" then it the confidence should be reduced!
		- What happens if the evidence is a fact? There are no evidences supporting a simple fact, right?
	- Do we have citations/references in the files? Sentences with citations to other work (e.g. scientific papers) are potentially more sustained ...

**Comment by anikethjr** [comment]
1. Sounds good, that's what I wanted to do...
2. I don't think we should be looking at this. The dataset is created under the assumption that everything in Wikipedia is true.

**Comment by diegoesteves** [comment]
It's better to have a call so that I can catch up here, but
1) Agree, sounds fine. 
2) Agree to, if something isn't true, they remove it. Meaning, FEVER dataset is gold standard, since it was manually annotated.

**Comment by pedrojlazevedo** [comment]
In order to answer this question, it was created a Random Forest model to handle this issue.
I changed the label of this issue to Future Work. 
This can be really important guidelines and scientific research:
- Improve the current Random Forest model to create the final label.
- Create a veracity checker.  For example: this could happen by placing the current gold_labels of FEVER dataset and verify by retrieving current knowledge. 

@GilRocha verify this change of label
