### ISSUE TITLE
To fix DeFacto bug on predicting

### ISSUE THREAD

**Issue by diegoesteves** [DeFacto/DeFactoNLP#5]
Hi Ismail,

please consider fixing the bug you found here https://github.com/DeFacto/DeFactoNLP/blob/master/rte/rte.py

Line 65:  numberOfPredictionsPerLabel= np.asarray([len(nonePredictions), len(supportPredictions), len(contradictionPredictions)])

Thanks!
;-)

**Comment by pedrojlazevedo** [comment]
This bug doesn't affect any part of the pipeline.
Nonetheless, this bug already fixed on the "new_metrics" branch.
