### ISSUE TITLE
Instructions to run DeFactoNLP

### ISSUE THREAD

**Issue by sergiogcharles** [DeFacto/DeFactoNLP#8]
Are there instructions to run DeFactoNLP? Thanks!

**Comment by diegoesteves** [comment]
We have just released [v1.0](https://github.com/DeFacto/DeFactoNLP/releases). @pedrojlazevedo has created a clean and organized [README](https://github.com/DeFacto/DeFactoNLP/blob/master/README.md)

Please check it out and let us know if something does not work properly! 

Ps: a new version coming soon! ;-)

**Comment by sergiogcharles** [comment]
Awesome, thanks so much! :)
